# Generated by Django 6.0.3 on 2026-04-20 14:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0002_category_deleted_at_category_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerprofile",
            name="rating_avg",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=3,
                verbose_name="Média de avaliações",
            ),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="rating_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Quantidade de avaliações"
            ),
        ),
    ]
