# Generated by Django 6.0.3 on 2026-04-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0003_providerprofile_rating_avg_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("provider", "platform", "value"),
                name="unique_active_contact_per_provider",
            ),
        ),
    ]
