# Generated by Django 6.0.3 on 2026-04-21

from django.db import migrations


def create_missing_client_profiles(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    ClientProfile = apps.get_model("accounts", "ClientProfile")
    db_alias = schema_editor.connection.alias

    existing_user_ids = set(
        ClientProfile.objects.using(db_alias).values_list("user_id", flat=True)
    )

    user_ids = User.objects.using(db_alias).exclude(id__in=existing_user_ids).values_list(
        "id", flat=True
    )

    for user_id in user_ids:
        ClientProfile.objects.using(db_alias).create(user_id=user_id)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_clientprofile_deleted_at_clientprofile_is_deleted_and_more"),
    ]

    operations = [
        migrations.RunPython(
            create_missing_client_profiles,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
