# Generated by Django 6.0.3 on 2026-04-20 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0003_providerprofile_rating_avg_and_more"),
        ("reviews", "0002_review_deleted_at_review_is_deleted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="review",
            name="unique_review_per_client",
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("provider", "client"),
                name="unique_review_per_client",
            ),
        ),
    ]
